<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="generator" content="rustdoc"><meta name="description" content="Defines a new exception type."><title>create_exception in pyo3 - Rust</title><script>if(window.location.protocol!=="file:")document.head.insertAdjacentHTML("beforeend","SourceSerif4-Regular-6b053e98.ttf.woff2,FiraSans-Regular-0fe48ade.woff2,FiraSans-Medium-e1aa3f0a.woff2,SourceCodePro-Regular-8badfe75.ttf.woff2,SourceCodePro-Semibold-aa29a496.ttf.woff2".split(",").map(f=>`<link rel="preload" as="font" type="font/woff2" crossorigin href="../static.files/${f}">`).join(""))</script><link rel="stylesheet" href="../static.files/normalize-9960930a.css"><link rel="stylesheet" href="../static.files/rustdoc-46132b98.css"><meta name="rustdoc-vars" data-root-path="../" data-static-root-path="../static.files/" data-current-crate="pyo3" data-themes="" data-resource-suffix="" data-rustdoc-version="1.85.1 (4eb161250 2025-03-15)" data-channel="1.85.1" data-search-js="search-75f5ac3e.js" data-settings-js="settings-0f613d39.js" ><script src="../static.files/storage-59e33391.js"></script><script defer src="sidebar-items.js"></script><script defer src="../static.files/main-5f194d8c.js"></script><noscript><link rel="stylesheet" href="../static.files/noscript-893ab5e7.css"></noscript><link rel="alternate icon" type="image/png" href="../static.files/favicon-32x32-6580c154.png"><link rel="icon" type="image/svg+xml" href="../static.files/favicon-044be391.svg"></head><body class="rustdoc macro"><!--[if lte IE 11]><div class="warning">This old browser is unsupported and will most likely display funky things.</div><![endif]--><nav class="mobile-topbar"><button class="sidebar-menu-toggle" title="show sidebar"></button></nav><nav class="sidebar"><div class="sidebar-crate"><h2><a href="../pyo3/index.html">pyo3</a><span class="version">0.24.1</span></h2></div><div class="sidebar-elems"><section id="rustdoc-toc"><h2 class="location"><a href="#">create_<wbr>exception</a></h2><h3><a href="#">Sections</a></h3><ul class="block top-toc"><li><a href="#syntax" title="Syntax">Syntax</a></li><li><a href="#examples" title="Examples">Examples</a></li></ul></section><div id="rustdoc-modnav"><h2 class="in-crate"><a href="index.html">In crate pyo3</a></h2></div></div></nav><div class="sidebar-resizer"></div><main><div class="width-limiter"><rustdoc-search></rustdoc-search><section id="main-content" class="content"><div class="main-heading"><span class="rustdoc-breadcrumbs"><a href="index.html">pyo3</a></span><h1>Macro <span class="macro">create_exception</span><button id="copy-path" title="Copy item path to clipboard">Copy item path</button></h1><rustdoc-toolbar></rustdoc-toolbar><span class="sub-heading"><a class="src" href="../src/pyo3/exceptions.rs.html#213-233">Source</a> </span></div><pre class="rust item-decl"><code>macro_rules! create_exception {
    ($module: expr, $name: ident, $base: ty) =&gt; { ... };
    ($module: expr, $name: ident, $base: ty, $doc: expr) =&gt; { ... };
}</code></pre><details class="toggle top-doc" open><summary class="hideme"><span>Expand description</span></summary><div class="docblock"><p>Defines a new exception type.</p>
<h2 id="syntax"><a class="doc-anchor" href="#syntax">§</a>Syntax</h2>
<ul>
<li><code>module</code> is the name of the containing module.</li>
<li><code>name</code> is the name of the new exception type.</li>
<li><code>base</code> is the base class of <code>MyError</code>, usually <a href="exceptions/struct.PyException.html" title="struct pyo3::exceptions::PyException"><code>PyException</code></a>.</li>
<li><code>doc</code> (optional) is the docstring visible to users (with <code>.__doc__</code> and <code>help()</code>) and</li>
</ul>
<p>accompanies your error type in your crate’s documentation.</p>
<h2 id="examples"><a class="doc-anchor" href="#examples">§</a>Examples</h2>
<div class="example-wrap"><pre class="rust rust-example-rendered"><code><span class="kw">use </span>pyo3::prelude::<span class="kw-2">*</span>;
<span class="kw">use </span>pyo3::create_exception;
<span class="kw">use </span>pyo3::exceptions::PyException;

<span class="macro">create_exception!</span>(my_module, MyError, PyException, <span class="string">"Some description."</span>);

<span class="attr">#[pyfunction]
</span><span class="kw">fn </span>raise_myerror() -&gt; PyResult&lt;()&gt; {
    <span class="kw">let </span>err = MyError::new_err(<span class="string">"Some error happened."</span>);
    <span class="prelude-val">Err</span>(err)
}

<span class="attr">#[pymodule]
</span><span class="kw">fn </span>my_module(m: <span class="kw-2">&amp;</span>Bound&lt;<span class="lifetime">'_</span>, PyModule&gt;) -&gt; PyResult&lt;()&gt; {
    m.add(<span class="string">"MyError"</span>, m.py().get_type::&lt;MyError&gt;())<span class="question-mark">?</span>;
    m.add_function(<span class="macro">wrap_pyfunction!</span>(raise_myerror, m)<span class="question-mark">?</span>)<span class="question-mark">?</span>;
    <span class="prelude-val">Ok</span>(())
}</code></pre></div>
<p>Python code can handle this exception like any other exception:</p>
<div class="example-wrap"><pre class="language-python"><code>from my_module import MyError, raise_myerror

try:
    raise_myerror()
except MyError as e:
    assert e.__doc__ == &#39;Some description.&#39;
    assert str(e) == &#39;Some error happened.&#39;</code></pre></div></div></details></section></div></main></body></html>